---
title: "Perisphere Template: Results Report - Main Analysis"
subtitle: "Start here when making deliverables with MS Word"
author: "[Byron C. Jaeger, PhD](https://www.byronjaeger.com/)"
date: "Document created on `r format(Sys.time(), '%B %d, %Y')`" 
bibliography: refs.bib
csl: refs.csl
always_allow_html: true
output: 
  officedown::rdocx_document:
    reference_docx: perisphere_template.docx
    keep_md: true
    toc: true
    toc_depth: 2
---

```{r setup-knitr, include=FALSE}

knitr::opts_chunk$set(
  echo = FALSE,    # don't show code blocks
  message = FALSE, # don't print messages to the doc
  warning = FALSE, # don't print warnings to the doc
  dpi = 300,       # higher dpi => higher render time 
  fig.width = 6,   # default figure width in inches
  fig.height = 4   # default figure height in inches
)

# Hello! This is the template word document for Perisphere reports.
# There are several code chunks used to set up the format of the
# document below. You don't have to modify those unless you want 
# to change the format of your output. 

```

```{r setup-pkgs}

# packages are usually handled by packages.R (in main directory).
# When tar_make() is run, it loads everything in packages.R.
# Assuming this document is in the list of targets (see ?tar_render),
# you won't need to include the library calls below.
# however, the template includes packages in its initial form
# so that you can knit the document without having to run tar_make().

# standards for word docs
library(officer)
library(flextable)

# specify a rounding specification 
library(table.glue)

# general purpose
library(tidyverse)
library(pericircle)

# table 1
library(gtsummary)

```

```{r setup-figures}

set_fig_landscape <- function() {
  knitr::opts_chunk$set(fig.width = 11, fig.height = 6)
}

set_fig_portrait <- function() {
  knitr::opts_chunk$set(fig.width = 6, fig.height = 4)
}

theme_set(
  new = theme_bw() + 
    theme(panel.grid = element_blank(),
          text = element_text(size = 12))
)

```

```{r setup-margins}

# Set a default footer because when we use block_section, it 
# starts a new style template for headers and footers. Thus,
# if we want page numbers to appear on every page, we need to
# put that into the default footer and then put that default
# footer into every block section. MS word...¯\_(ツ)_/¯
# note to future self - go here if you want to remember this: 
# https://github.com/davidgohel/officedown/discussions/103

footer_default <- block_list(
  fpar(
    run_word_field(field = "PAGE"),
    fp_p = fp_par(text.align = "left") 
  )
)

# Code in this chunk sets the margins for your document. 
# The helper functions page_long_above() and page_wide_above()
# also provide shortcuts for switching between wide (landscape)
# and normal (long) MS word layouts. 

# helper function for defining margins
make_margin <- function(x=NULL){
  
  if(is.null(x)){ return(page_mar()) } 
  
  if(is.character(x)){
    
    out <- switch(
      tolower(x),
      "normal" = page_mar(1, 1, 1, 1),
      "narrow" = page_mar(1/2, 1/2, 1/2, 1/2),
      "moderate" = page_mar(1, 1, 3/4, 3/4)
    )
    
  }
  
}

# set content above to be portrait
page_long_above <- function(margins = make_margin('narrow')){
  
  # b/c block_sections apply to content ABOVE, we set
  # the content BELOW to be landscape when we use page_long_above  
  set_fig_landscape()
  
  block_section(
    prop_section(
      page_size = page_size(orient = "portrait"),
      type = "continuous",
      page_margins = margins,
      footer_default = footer_default
    )
  )
  
}

# set content above to be landscape
page_wide_above <- function(margins = make_margin('narrow')){
  
  # b/c block_sections apply to content ABOVE, we set
  # the content BELOW to be portrait when we use page_wide_above
  set_fig_portrait()
  
  block_section(
    prop_section(
      page_size = page_size(orient = "landscape"),
      type = "continuous",
      page_margins = margins,
      footer_default = footer_default
    )
  )
  
}

```

```{r setup-targets}

withr::with_dir(
  new = here::here(),
  code = {
    targets::tar_load(names = c(characteristics_main))
  }
)

```

```{r setup-formatters}

# make a short name for table.glue::table_value - this makes
# the inline reporting of results less complicated to read.
tv <- table.glue::table_value
tg <- table.glue::table_glue

r_version <- tg("{version$major}.{version$minor}")

```

```{r setup-tables}

# abbreviation management

abbrvs <- list(
  CI   = 'confidence interval',
  SD   = 'standard deviation',
  IQR  = 'interquartile range',
  EHR  = 'electronic health records',
  CVD  = 'cardiovascular disease'
)

abbrvs_paste <- function(strings){
  
  front <- 'Abbreviations'
  
  matter <- glue::glue_collapse(strings, sep = '; ', last = '; and ')
  
  paste(front, matter, sep = ': ')
  
}

abbrvs_write <- function(abbr){
  
  sorted <- abbr[sort(names(abbr))]
  
  strings <- map2_chr(names(sorted), sorted, paste, sep = ' = ')
  
  abbrvs_paste(strings)
  
}


```


\newpage

## Table 1: Characteristics

```{r}
characteristics_main
```
